### PR TITLE
feat: add Ashley Down

### PR DESCRIPTION
**Pull request by ascorbic**
Adds Ashley Down station, which is now open. Coordinates from wikipedia

### CODE REVIEW

**Comment by davwheat** [comment]
Thanks for the PR! I'm not sure why it's showing as editing every line of the file, so just to be safe I copied the appropriate data over manually in aad543652ab1d08e38da188225657146e74f52c7 instead.

**Comment by ascorbic** [comment]
Weird. It just shows as one line for me locally! Thanks for sorting it.

**Comment by davwheat** [comment]
I'll still need to publish a new release later when I'm at a computer since I never set this repo up for automated npm uploading. Hopefully by midnight tonight!

**Comment by ascorbic** [comment]
No worries. I'm using the file manually directly anyway, as it's in a Wear OS app.

**Pull request closed without merging**
